"""add personel id

Revision ID: 443b012aa976
Revises: 6dd329a910c1
Create Date: 2021-02-21 12:43:17.939162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443b012aa976'
down_revision = '6dd329a910c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('personel_id', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'employees', ['personel_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_column('employees', 'personel_id')
    # ### end Alembic commands ###
