"""add gender

Revision ID: d4afa327cd43
Revises: 443b012aa976
Create Date: 2021-02-21 19:27:44.883300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4afa327cd43'
down_revision = '443b012aa976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('gender', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'gender')
    # ### end Alembic commands ###
